name: Staging CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "16.16.0"
      - run: npm install
      # - run: npm test -- --coverage
      #   env:
      #     CI: true
      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/boilerplatevuejs:develop
